# Generated by Django 5.0 on 2024-10-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('date_of_register', models.DateField()),
                ('application_type', models.CharField(choices=[('emergency', 'Emergency'), ('planned', 'Planned'), ('superfix', 'Superfix')], max_length=10)),
            ],
        ),
    ]
